name: exifdart
version: 0.8.0-dev.1
description: Decode Exif data from jpeg files (Dart port based on https://github.com/exif-js/exif-js/)
homepage: https://www.github.com/psiroki/exifdart/
environment:
  sdk: '>=2.12.0 <3.0.0'
